name: Devvit Upload Github Action
description: Github Action for uploading Devvit apps

branding:
  icon: upload
  color: orange

inputs:
  refresh_token:
    description: Refresh Token for Devvit CLI authentication.
    required: true
  upload_args:
    description: Optional command line arguments for devvit upload.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: latest

    - run: npm install -g devvit
      shell: bash

    - name: Install Node modules
      shell: bash
      run: npm install

    - uses: actions/setup-python@v5

    - name: Install Python dependencies
      shell: bash
      run: pip install -r "${{ github.action_path }}/requirements.txt"

    - name: Create TOKEN file
      shell: bash
      run: python3 "${{ github.action_path }}/token_file.py" ${{ inputs.refresh_token }}

    - name: Devvit Upload
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME="${{ github.ref_name }}"
          BUMP_FLAG=$(python3 "${{ github.action_path }}/set_app_version.py" "$TAG_NAME")
          echo "Running: devvit upload $BUMP_FLAG"
          yes | devvit upload $BUMP_FLAG
        else
          echo "Running: devvit upload ${{ inputs.upload_args }}"
          devvit upload ${{ inputs.upload_args }}
        fi

    - name: Devvit Publish
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      shell: bash
      run: devvit publish
