name: Devvit Upload Github Action
description: Github Acotion for uploading Devvit apps

branding:
  icon: upload
  color: orange

inputs:
  refresh_token:
    description: Refresh Token for Devvit CLI authentication.
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: latest

    - run: npm install -g devvit
      shell: bash

    - name: Install Node modules
      shell: bash
      run: npm install

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Create TOKEN file
      shell: bash
      run: python "${{ github.action_path }}/token_file.py" ${{inputs.refresh_token}}

    - name: Upload to Devvit
      shell: bash
      run: devvit upload
